
package deltaiot.services;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeltaIoTWebService", targetNamespace = "http://services.deltaiot/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeltaIoTWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<deltaiot.services.Mote>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMotes", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetAllMotes")
    @ResponseWrapper(localName = "getAllMotesResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetAllMotesResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getAllMotesRequest", output = "http://services.deltaiot/DeltaIoTWebService/getAllMotesResponse")
    public List<Mote> getAllMotes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "setDefaultConfiguration", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.SetDefaultConfiguration")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/setDefaultConfiguration")
    public void setDefaultConfiguration(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<deltaiot.services.QoS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNetworkQoS", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetNetworkQoS")
    @ResponseWrapper(localName = "getNetworkQoSResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetNetworkQoSResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getNetworkQoSRequest", output = "http://services.deltaiot/DeltaIoTWebService/getNetworkQoSResponse")
    public List<QoS> getNetworkQoS(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoteEnergyLevel", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetMoteEnergyLevel")
    @ResponseWrapper(localName = "getMoteEnergyLevelResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetMoteEnergyLevelResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getMoteEnergyLevelRequest", output = "http://services.deltaiot/DeltaIoTWebService/getMoteEnergyLevelResponse")
    public double getMoteEnergyLevel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoteTrafficLoad", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetMoteTrafficLoad")
    @ResponseWrapper(localName = "getMoteTrafficLoadResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetMoteTrafficLoadResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getMoteTrafficLoadRequest", output = "http://services.deltaiot/DeltaIoTWebService/getMoteTrafficLoadResponse")
    public double getMoteTrafficLoad(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkPowerSetting", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkPowerSetting")
    @ResponseWrapper(localName = "getLinkPowerSettingResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkPowerSettingResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getLinkPowerSettingRequest", output = "http://services.deltaiot/DeltaIoTWebService/getLinkPowerSettingResponse")
    public int getLinkPowerSetting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkSpreadingFactor", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkSpreadingFactor")
    @ResponseWrapper(localName = "getLinkSpreadingFactorResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkSpreadingFactorResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getLinkSpreadingFactorRequest", output = "http://services.deltaiot/DeltaIoTWebService/getLinkSpreadingFactorResponse")
    public int getLinkSpreadingFactor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkSignalNoise", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkSignalNoise")
    @ResponseWrapper(localName = "getLinkSignalNoiseResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkSignalNoiseResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getLinkSignalNoiseRequest", output = "http://services.deltaiot/DeltaIoTWebService/getLinkSignalNoiseResponse")
    public double getLinkSignalNoise(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkDistributionFactor", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkDistributionFactor")
    @ResponseWrapper(localName = "getLinkDistributionFactorResponse", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.GetLinkDistributionFactorResponse")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/getLinkDistributionFactorRequest", output = "http://services.deltaiot/DeltaIoTWebService/getLinkDistributionFactorResponse")
    public double getLinkDistributionFactor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "setMoteSettings", targetNamespace = "http://services.deltaiot/", className = "deltaiot.services.SetMoteSettings")
    @Action(input = "http://services.deltaiot/DeltaIoTWebService/setMoteSettings")
    public void setMoteSettings(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<LinkSettings> arg2);

}
