
package deltaiot.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeltaIoTWebServiceService", targetNamespace = "http://services.deltaiot/", wsdlLocation = "http://172.21.0.11:8080/DeltaIoTServices/DeltaIoTWebServiceService?WSDL")
public class DeltaIoTWebServiceService
    extends Service
{

    private final static URL DELTAIOTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DELTAIOTWEBSERVICESERVICE_EXCEPTION;
    private final static QName DELTAIOTWEBSERVICESERVICE_QNAME = new QName("http://services.deltaiot/", "DeltaIoTWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.21.0.11:8080/DeltaIoTServices/DeltaIoTWebServiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELTAIOTWEBSERVICESERVICE_WSDL_LOCATION = url;
        DELTAIOTWEBSERVICESERVICE_EXCEPTION = e;
    }

    public DeltaIoTWebServiceService() {
        super(__getWsdlLocation(), DELTAIOTWEBSERVICESERVICE_QNAME);
    }

    public DeltaIoTWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELTAIOTWEBSERVICESERVICE_QNAME, features);
    }

    public DeltaIoTWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, DELTAIOTWEBSERVICESERVICE_QNAME);
    }

    public DeltaIoTWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELTAIOTWEBSERVICESERVICE_QNAME, features);
    }

    public DeltaIoTWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeltaIoTWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeltaIoTWebService
     */
    @WebEndpoint(name = "DeltaIoTWebServicePort")
    public DeltaIoTWebService getDeltaIoTWebServicePort() {
        return super.getPort(new QName("http://services.deltaiot/", "DeltaIoTWebServicePort"), DeltaIoTWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeltaIoTWebService
     */
    @WebEndpoint(name = "DeltaIoTWebServicePort")
    public DeltaIoTWebService getDeltaIoTWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.deltaiot/", "DeltaIoTWebServicePort"), DeltaIoTWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELTAIOTWEBSERVICESERVICE_EXCEPTION!= null) {
            throw DELTAIOTWEBSERVICESERVICE_EXCEPTION;
        }
        return DELTAIOTWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
